/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TaxReliefRouteImport } from './routes/tax-relief'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PersonalLoansRouteImport } from './routes/personal-loans'
import { Route as GetHelpRouteImport } from './routes/get-help'
import { Route as DebtReliefRouteImport } from './routes/debt-relief'
import { Route as CreditRepairRouteImport } from './routes/credit-repair'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsumerRightsRouteImport } from './routes/consumer-rights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxReliefRoute = TaxReliefRouteImport.update({
  id: '/tax-relief',
  path: '/tax-relief',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalLoansRoute = PersonalLoansRouteImport.update({
  id: '/personal-loans',
  path: '/personal-loans',
  getParentRoute: () => rootRouteImport,
} as any)
const GetHelpRoute = GetHelpRouteImport.update({
  id: '/get-help',
  path: '/get-help',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtReliefRoute = DebtReliefRouteImport.update({
  id: '/debt-relief',
  path: '/debt-relief',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditRepairRoute = CreditRepairRouteImport.update({
  id: '/credit-repair',
  path: '/credit-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerRightsRoute = ConsumerRightsRouteImport.update({
  id: '/consumer-rights',
  path: '/consumer-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-rights': typeof ConsumerRightsRoute
  '/contact': typeof ContactRoute
  '/credit-repair': typeof CreditRepairRoute
  '/debt-relief': typeof DebtReliefRoute
  '/get-help': typeof GetHelpRoute
  '/personal-loans': typeof PersonalLoansRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-relief': typeof TaxReliefRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-rights': typeof ConsumerRightsRoute
  '/contact': typeof ContactRoute
  '/credit-repair': typeof CreditRepairRoute
  '/debt-relief': typeof DebtReliefRoute
  '/get-help': typeof GetHelpRoute
  '/personal-loans': typeof PersonalLoansRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-relief': typeof TaxReliefRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consumer-rights': typeof ConsumerRightsRoute
  '/contact': typeof ContactRoute
  '/credit-repair': typeof CreditRepairRoute
  '/debt-relief': typeof DebtReliefRoute
  '/get-help': typeof GetHelpRoute
  '/personal-loans': typeof PersonalLoansRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-relief': typeof TaxReliefRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consumer-rights'
    | '/contact'
    | '/credit-repair'
    | '/debt-relief'
    | '/get-help'
    | '/personal-loans'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax-relief'
    | '/terms'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consumer-rights'
    | '/contact'
    | '/credit-repair'
    | '/debt-relief'
    | '/get-help'
    | '/personal-loans'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax-relief'
    | '/terms'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consumer-rights'
    | '/contact'
    | '/credit-repair'
    | '/debt-relief'
    | '/get-help'
    | '/personal-loans'
    | '/privacy'
    | '/sitemap.xml'
    | '/tax-relief'
    | '/terms'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsumerRightsRoute: typeof ConsumerRightsRoute
  ContactRoute: typeof ContactRoute
  CreditRepairRoute: typeof CreditRepairRoute
  DebtReliefRoute: typeof DebtReliefRoute
  GetHelpRoute: typeof GetHelpRoute
  PersonalLoansRoute: typeof PersonalLoansRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxReliefRoute: typeof TaxReliefRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-relief': {
      id: '/tax-relief'
      path: '/tax-relief'
      fullPath: '/tax-relief'
      preLoaderRoute: typeof TaxReliefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-loans': {
      id: '/personal-loans'
      path: '/personal-loans'
      fullPath: '/personal-loans'
      preLoaderRoute: typeof PersonalLoansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-help': {
      id: '/get-help'
      path: '/get-help'
      fullPath: '/get-help'
      preLoaderRoute: typeof GetHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debt-relief': {
      id: '/debt-relief'
      path: '/debt-relief'
      fullPath: '/debt-relief'
      preLoaderRoute: typeof DebtReliefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-repair': {
      id: '/credit-repair'
      path: '/credit-repair'
      fullPath: '/credit-repair'
      preLoaderRoute: typeof CreditRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumer-rights': {
      id: '/consumer-rights'
      path: '/consumer-rights'
      fullPath: '/consumer-rights'
      preLoaderRoute: typeof ConsumerRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsumerRightsRoute: ConsumerRightsRoute,
  ContactRoute: ContactRoute,
  CreditRepairRoute: CreditRepairRoute,
  DebtReliefRoute: DebtReliefRoute,
  GetHelpRoute: GetHelpRoute,
  PersonalLoansRoute: PersonalLoansRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxReliefRoute: TaxReliefRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
